---
- name: install httpd
  yum: name=httpd state=installed
- name: copy index.html
  copy: src=index.html dest=/var/www/html/index.html
- name: copy abc.conf.j2
  template: src=abc.conf.j2 dest=/root/abc.conf.j2
